CREATE TYPE role_enum AS ENUM (
    'ROLE_USER',
    'ROLE_AGENT',
    'ROLE_ADMIN'
    );

CREATE TYPE status_enum AS ENUM (
    'WAITING',
    'CALLED',
    'PROCESSING',
    'COMPLETE',
    'CANCELED'
    );

CREATE TABLE "group"
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(100) NOT NULL,
    called_at    TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    is_complete  BOOLEAN DEFAULT FALSE
);

CREATE TABLE "user"
(
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name              VARCHAR(100) NOT NULL,
    phone_number      VARCHAR(20)  NOT NULL UNIQUE,
    role              role_enum    NOT NULL DEFAULT 'ROLE_USER',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    is_phone_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    group_id          BIGINT REFERENCES "group" (id) ON DELETE NO ACTION
);

CREATE TABLE ticket
(
    user_id      BIGINT REFERENCES "user" (id) ON DELETE CASCADE UNIQUE,
    group_id     BIGINT REFERENCES "group" (id) ON DELETE NO ACTION NOT NULL,
    number       BIGINT                                             NOT NULL UNIQUE,
    status       status_enum                                        NOT NULL DEFAULT 'WAITING',
    created_at   TIMESTAMPTZ                                        NOT NULL DEFAULT now(),
    called_at    TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (user_id, group_id)
);

CREATE INDEX idx_ticket_status_number ON ticket (status, number);
CREATE INDEX idx_ticket_group_id ON ticket (group_id);
CREATE table test()



